import {
  DropdownContent,
  DropdownGroup,
  DropdownItem,
  DropdownItemHint,
  DropdownItemIcon,
  DropdownItemIndicator,
  DropdownItemLabel,
  DropdownLabel,
  DropdownPopover,
  DropdownRoot,
  DropdownSeparator,
  DropdownSub,
  DropdownSubContent,
  DropdownSubTrigger,
  DropdownTrigger,
} from "./Dropdown";

export const Dropdown = Object.assign(DropdownRoot, {
  Trigger: DropdownTrigger,
  Popover: DropdownPopover,
  Content: DropdownContent,
  Group: DropdownGroup,
  Label: DropdownLabel,
  Separator: DropdownSeparator,
  Item: DropdownItem,
  ItemLabel: DropdownItemLabel,
  ItemHint: DropdownItemHint,
  ItemIcon: DropdownItemIcon,
  ItemIndicator: DropdownItemIndicator,
  Sub: DropdownSub,
  SubTrigger: DropdownSubTrigger,
  SubContent: DropdownSubContent,
});

export {
  DropdownTrigger,
  DropdownPopover,
  DropdownContent,
  DropdownGroup,
  DropdownLabel,
  DropdownSeparator,
  DropdownItem,
  DropdownItemLabel,
  DropdownItemHint,
  DropdownItemIcon,
  DropdownItemIndicator,
  DropdownSub,
  DropdownSubTrigger,
  DropdownSubContent,
} from "./Dropdown";

export type {
  DropdownProps,
  DropdownTriggerProps,
  DropdownPopoverProps,
  DropdownContentProps,
  DropdownGroupProps,
  DropdownLabelProps,
  DropdownSeparatorProps,
  DropdownItemProps,
  DropdownItemLabelProps,
  DropdownItemHintProps,
  DropdownItemIconProps,
  DropdownItemIndicatorProps,
  DropdownItemVariant,
  DropdownSubProps,
  DropdownSubTriggerProps,
  DropdownSubContentProps,
} from "./Dropdown";
