import { AccordionBody, AccordionContent, AccordionDescription, AccordionHeading, AccordionIcon, AccordionChevron, AccordionItem, AccordionMessage, AccordionPanel, AccordionRoot, AccordionTitle, AccordionTrigger } from "./Accordion";

export const Accordion = Object.assign(AccordionRoot, {
  Item: AccordionItem,
  Heading: AccordionHeading,
  Trigger: AccordionTrigger,
  Message: AccordionMessage,
  Icon: AccordionIcon,
  Content: AccordionContent,
  Title: AccordionTitle,
  Description: AccordionDescription,
  Chevron: AccordionChevron,
  Panel: AccordionPanel,
  Body: AccordionBody,
});

export {
  AccordionRoot,
  AccordionItem,
  AccordionHeading,
  AccordionTrigger,
  AccordionMessage,
  AccordionIcon,
  AccordionContent,
  AccordionTitle,
  AccordionDescription,
  AccordionChevron,
  AccordionPanel,
  AccordionBody,
  type AccordionProps,
  type AccordionItemProps,
  type AccordionHeadingProps,
  type AccordionTriggerProps,
  type AccordionMessageProps,
  type AccordionIconProps,
  type AccordionContentProps,
  type AccordionTitleProps,
  type AccordionDescriptionProps,
  type AccordionChevronProps,
  type AccordionPanelProps,
  type AccordionBodyProps,
} from "./Accordion";
