export type {
  AccordionProps,
  AccordionItemProps,
  AccordionHeadingProps,
  AccordionTriggerProps,
  AccordionMessageProps,
  AccordionIconProps,
  AccordionContentProps,
  AccordionTitleProps,
  AccordionDescriptionProps,
  AccordionIndicatorProps,
  AccordionPanelProps,
  AccordionBodyProps,
} from "./Accordion.types";
import {
  AccordionBody,
  AccordionContent,
  AccordionDescription,
  AccordionHeading,
  AccordionIcon,
  AccordionIndicator,
  AccordionItem,
  AccordionMessage,
  AccordionPanel,
  AccordionRoot,
  AccordionTitle,
  AccordionTrigger,
} from "./Accordion";

export const Accordion = Object.assign(AccordionRoot, {
  Item: AccordionItem,
  Heading: AccordionHeading,
  Trigger: AccordionTrigger,
  Message: AccordionMessage,
  Icon: AccordionIcon,
  Content: AccordionContent,
  Title: AccordionTitle,
  Description: AccordionDescription,
  Indicator: AccordionIndicator,
  Panel: AccordionPanel,
  Body: AccordionBody,
});
