import type { ThemeColors } from "./themeDefaults";

/**
 * Default dark/light palettes — flat ThemeColors snapshots (same shape as Copy config).
 * Named presets live on the docs site / playground.
 */

const DARK_RIPPLE = {
  convergeRipplePrimaryFill:
    "color-mix(in oklab, var(--color-primary-foreground) 38%, transparent)",
  convergeRippleNeutral: "var(--color-primary-tint-strong)",
  convergeRippleNeutralMuted: "color-mix(in oklab, var(--color-primary) 14%, transparent)",
  convergeRippleDanger: "color-mix(in oklab, var(--color-danger-foreground) 38%, transparent)",
  convergeRippleSuccess:
    "color-mix(in oklab, var(--color-success-foreground) 38%, transparent)",
  convergeRippleInfo: "color-mix(in oklab, var(--color-info-foreground) 38%, transparent)",
  convergeRippleWarning:
    "color-mix(in oklab, var(--color-warning-foreground) 38%, transparent)",
} as const;

const LIGHT_RIPPLE = {
  convergeRipplePrimaryFill:
    "color-mix(in oklab, var(--color-primary-foreground) 52%, var(--color-primary))",
  convergeRippleNeutral: "var(--color-primary-tint-strong)",
  convergeRippleNeutralMuted: "color-mix(in oklab, var(--color-primary) 14%, transparent)",
  convergeRippleDanger: "color-mix(in oklab, var(--color-danger-foreground) 38%, transparent)",
  convergeRippleSuccess:
    "color-mix(in oklab, var(--color-success-foreground) 38%, transparent)",
  convergeRippleInfo: "color-mix(in oklab, var(--color-info-foreground) 38%, transparent)",
  convergeRippleWarning:
    "color-mix(in oklab, var(--color-warning-foreground) 38%, transparent)",
} as const;

export const DARK_COLORS: ThemeColors = {
  background: "#0c0d10",
  surface: "#171717",
  secondary: "color-mix(in oklab, var(--color-foreground) 12%, var(--color-surface))",
  secondaryForeground: "var(--color-foreground)",
  tertiary: "color-mix(in oklab, var(--color-foreground) 24%, var(--color-surface))",
  tertiaryForeground: "var(--color-foreground)",
  border: "color-mix(in oklab, var(--color-foreground) 12%, transparent)",
  shadow: "#000000",
  shadowSecondary: "#000000",
  foreground: "#f4f5f7",
  muted: "color-mix(in oklab, var(--color-foreground) 6%, var(--color-surface))",
  mutedForeground: "#858994",
  primary: "#ebebef",
  primaryForeground: "#0c0c0e",
  primaryTint: "color-mix(in oklab, var(--color-primary) 20%, transparent)",
  primaryTintStrong: "color-mix(in oklab, var(--color-primary) 25%, transparent)",
  focusRing: "color-mix(in oklab, var(--color-primary) 60%, transparent)",
  focusRingDanger: "color-mix(in oklab, var(--color-danger) 60%, transparent)",
  focusRingSuccess: "color-mix(in oklab, var(--color-success) 60%, transparent)",
  focusRingInfo: "color-mix(in oklab, var(--color-info) 60%, transparent)",
  focusRingWarning: "color-mix(in oklab, var(--color-warning) 60%, transparent)",
  indicator: "#ebebef",
  indicatorForeground: "#0c0c0e",
  danger: "#d73737",
  success: "#35b664",
  info: "#389dcc",
  warning: "#daa13e",
  dangerForeground: "#fafafa",
  successForeground: "#fafafa",
  infoForeground: "#fafafa",
  warningForeground: "#0c0c0e",
  primaryHover: "color-mix(in oklab, var(--color-primary) 80%, var(--color-surface))",
  defaultHover: "color-mix(in oklab, var(--color-foreground) 8%, var(--color-surface))",
  transparentHover: "color-mix(in oklab, var(--color-muted) 70%, transparent)",
  secondaryHover: "color-mix(in oklab, var(--color-foreground) 6%, var(--color-secondary))",
  tertiaryHover: "color-mix(in oklab, var(--color-foreground) 6%, var(--color-tertiary))",
  surfaceTintDanger: "color-mix(in oklab, var(--color-danger) 15%, transparent)",
  surfaceTintDangerHover: "color-mix(in oklab, var(--color-danger) 25%, transparent)",
  dangerFillHover: "color-mix(in oklab, var(--color-danger) 80%, transparent)",
  surfaceTintSuccess: "color-mix(in oklab, var(--color-success) 15%, transparent)",
  surfaceTintSuccessHover: "color-mix(in oklab, var(--color-success) 25%, transparent)",
  successFillHover: "color-mix(in oklab, var(--color-success) 80%, transparent)",
  surfaceTintInfo: "color-mix(in oklab, var(--color-info) 15%, transparent)",
  surfaceTintInfoHover: "color-mix(in oklab, var(--color-info) 25%, transparent)",
  infoFillHover: "color-mix(in oklab, var(--color-info) 80%, transparent)",
  surfaceTintWarning: "color-mix(in oklab, var(--color-warning) 15%, transparent)",
  surfaceTintWarningHover: "color-mix(in oklab, var(--color-warning) 25%, transparent)",
  warningFillHover: "color-mix(in oklab, var(--color-warning) 80%, transparent)",
  ...DARK_RIPPLE,
};

export const LIGHT_COLORS: ThemeColors = {
  background: "#f5f5f5",
  surface: "#ffffff",
  secondary: "color-mix(in oklab, var(--color-foreground) 12%, var(--color-surface))",
  secondaryForeground: "var(--color-foreground)",
  tertiary: "color-mix(in oklab, var(--color-foreground) 24%, var(--color-surface))",
  tertiaryForeground: "var(--color-foreground)",
  border: "color-mix(in oklab, var(--color-foreground) 12%, transparent)",
  shadow: "#000000",
  shadowSecondary: "#000000",
  foreground: "#18181b",
  muted: "color-mix(in oklab, var(--color-foreground) 12%, var(--color-surface))",
  mutedForeground: "#646467",
  primary: "#18181b",
  primaryForeground: "#fafafa",
  primaryTint: "color-mix(in oklab, var(--color-primary) 20%, transparent)",
  primaryTintStrong: "color-mix(in oklab, var(--color-primary) 25%, transparent)",
  focusRing: "color-mix(in oklab, var(--color-primary) 60%, transparent)",
  focusRingDanger: "color-mix(in oklab, var(--color-danger) 60%, transparent)",
  focusRingSuccess: "color-mix(in oklab, var(--color-success) 60%, transparent)",
  focusRingInfo: "color-mix(in oklab, var(--color-info) 60%, transparent)",
  focusRingWarning: "color-mix(in oklab, var(--color-warning) 60%, transparent)",
  indicator: "#18181b",
  indicatorForeground: "#fafafa",
  danger: "#df4e4e",
  success: "#2ebd62",
  info: "#31a0d3",
  warning: "#e1a53d",
  dangerForeground: "#ffffff",
  successForeground: "#ffffff",
  infoForeground: "#ffffff",
  warningForeground: "#0c0c0e",
  primaryHover: "color-mix(in oklab, var(--color-primary) 90%, var(--color-surface))",
  defaultHover: "color-mix(in oklab, var(--color-foreground) 8%, var(--color-surface))",
  transparentHover: "color-mix(in oklab, var(--color-muted) 70%, transparent)",
  secondaryHover: "color-mix(in oklab, var(--color-foreground) 6%, var(--color-secondary))",
  tertiaryHover: "color-mix(in oklab, var(--color-foreground) 6%, var(--color-tertiary))",
  surfaceTintDanger: "color-mix(in oklab, var(--color-danger) 15%, transparent)",
  surfaceTintDangerHover: "color-mix(in oklab, var(--color-danger) 25%, transparent)",
  dangerFillHover: "color-mix(in oklab, var(--color-danger) 80%, transparent)",
  surfaceTintSuccess: "color-mix(in oklab, var(--color-success) 15%, transparent)",
  surfaceTintSuccessHover: "color-mix(in oklab, var(--color-success) 25%, transparent)",
  successFillHover: "color-mix(in oklab, var(--color-success) 80%, transparent)",
  surfaceTintInfo: "color-mix(in oklab, var(--color-info) 15%, transparent)",
  surfaceTintInfoHover: "color-mix(in oklab, var(--color-info) 25%, transparent)",
  infoFillHover: "color-mix(in oklab, var(--color-info) 80%, transparent)",
  surfaceTintWarning: "color-mix(in oklab, var(--color-warning) 15%, transparent)",
  surfaceTintWarningHover: "color-mix(in oklab, var(--color-warning) 25%, transparent)",
  warningFillHover: "color-mix(in oklab, var(--color-warning) 80%, transparent)",
  ...LIGHT_RIPPLE,
};
