import {
  DrawerBackdropInner,
  DrawerBody,
  DrawerClose,
  DrawerContent,
  DrawerDescription,
  DrawerFooter,
  DrawerHandleInner,
  DrawerHeader,
  DrawerHeadingBlock,
  DrawerPanel,
  DrawerRoot,
  DrawerTitle,
  DrawerTrigger,
} from "./Drawer";

export const Drawer = Object.assign(DrawerRoot, {
  Trigger: DrawerTrigger,
  Panel: DrawerPanel,
  Backdrop: DrawerBackdropInner,
  Handle: DrawerHandleInner,
  Content: DrawerContent,
  Header: DrawerHeader,
  HeadingBlock: DrawerHeadingBlock,
  Title: DrawerTitle,
  Description: DrawerDescription,
  Close: DrawerClose,
  Body: DrawerBody,
  Footer: DrawerFooter,
});

export type {
  DrawerProps,
  DrawerPanelProps,
  DrawerTriggerProps,
  DrawerPlacement,
  DrawerExtent,
  DrawerVariant,
  DrawerClassNames,
  DrawerBackdropProps,
  DrawerHandleProps,
  DrawerHeaderProps,
  DrawerHeadingBlockProps,
  DrawerTitleProps,
  DrawerDescriptionProps,
  DrawerBodyProps,
  DrawerFooterProps,
  DrawerCloseProps,
  DrawerContentProps,
} from "./drawerTypes";
