export { tokensConfig, type TokensConfig } from "./config";
export {
  burneFontWeightScale,
  FONT_WEIGHT_CSS_VAR,
  FONT_WEIGHT_DEFAULTS,
  fontWeightToken,
  type FontWeightStep,
} from "./fontWeights";
export {
  burneShadowScale,
  type ShadowSize,
  type ShadowLevel,
  SHADOW_CSS_VAR,
  SHADOW_LAYER_GEOM,
  SHADOW_OPACITY_BASE,
  SHADOW_SIZE_CSS_DEFAULT,
  shadowToken,
} from "./shadows";
export {
  TEXT_SCALE_BASES,
  type TextScaleStep,
} from "./textScale";
export {
  TOAST_SCRIM_CSS_VAR,
  TOAST_SCRIM_DEFAULTS,
  toastScrimToken,
  type ToastScrimCssVar,
} from "./toastScrim";
export {
  OVERLAY_BACKDROP_CSS_VAR,
  OVERLAY_BACKDROP_DEFAULTS,
  overlayBackdropToken,
  type OverlayBackdropCssVar,
} from "./overlayBackdrop";
export {
  burneZIndexScale,
  Z_INDEX_CSS_VAR,
  Z_INDEX_DEFAULTS,
  zIndexToken,
  type ZIndexLayer,
} from "./zIndex";

/** CSS variable names for type-safe access and generators */
export const designTokenNames = [
  "--border-width",
  "--focus-ring-width",
  "--focus-ring-offset",
  "--motion-surface-duration",
  "--motion-surface-ease",
  "--motion-shadow-ease",
  "--overlay-backdrop-color",
  "--overlay-backdrop-blur",
  "--overlay-backdrop-saturate",
  "--overlay-backdrop-scrim",
  "--z-dialog",
  "--z-dropdown",
  "--z-dropdown-sub",
  "--z-popover",
  "--z-toast",
  "--z-tooltip",
  "--color-background",
  "--color-surface",
  "--color-border",
  "--color-foreground",
  "--color-muted",
  "--color-primary",
  "--color-primary-foreground",
  "--color-primary-hover",
  "--color-default-hover",
  "--color-primary-tint",
  "--color-primary-tint-strong",
  "--color-indicator",
  "--color-indicator-foreground",
  "--color-secondary",
  "--color-secondary-foreground",
  "--color-secondary-hover",
  "--color-tertiary",
  "--color-tertiary-foreground",
  "--color-tertiary-hover",
  "--color-focus-ring",
  "--color-converge-ripple-primary-fill",
  "--color-converge-ripple-neutral",
  "--color-converge-ripple-neutral-muted",
  "--color-converge-ripple-danger",
  "--color-converge-ripple-info",
  "--color-converge-ripple-success",
  "--color-converge-ripple-warning",
  "--color-danger",
  "--color-danger-fill-hover",
  "--color-danger-foreground",
  "--color-success",
  "--color-success-foreground",
  "--color-success-fill-hover",
  "--color-info",
  "--color-info-foreground",
  "--color-info-fill-hover",
  "--color-warning",
  "--color-warning-foreground",
  "--color-warning-fill-hover",
  "--color-surface-tint-danger",
  "--color-surface-tint-success",
  "--color-surface-tint-info",
  "--color-surface-tint-warning",
  "--color-surface-tint-danger-hover",
  "--color-surface-tint-success-hover",
  "--color-surface-tint-info-hover",
  "--color-surface-tint-warning-hover",

  "--font-family-sans",
  "--font-family-mono",
  "--font-w-small",
  "--font-w-base",
  "--font-w-mid",
  "--font-w-strong",
  "--font-w-bold",
  "--space",
  "--space-xsmall",
  "--space-small",
  "--space-base",
  "--space-plus",
  "--space-mid",
  "--space-large",
  "--space-xlarge",
  "--size",
  "--size-scale-xsmall",
  "--size-scale-small",
  "--size-scale-base",
  "--size-scale-plus",
  "--size-scale-mid",
  "--size-scale-large",
  "--size-scale-xlarge",
  "--selection-indicator-small",
  "--selection-indicator-base",
  "--selection-indicator-mid",
  "--selection-indicator-large",
  "--radius",
  "--radius-value-xsmall",
  "--radius-value-small",
  "--radius-value-base",
  "--radius-value-mid",
  "--radius-value-large",
  "--text-scale-tools",
  "--text-scale-tools--line-height",
  "--text-scale-xsmall",
  "--text-scale-xsmall--line-height",
  "--text-scale-small",
  "--text-scale-small--line-height",
  "--text-scale-base",
  "--text-scale-base--line-height",
  "--text-scale-mid",
  "--text-scale-mid--line-height",
  "--text-scale-large",
  "--text-scale-large--line-height",
  "--text-scale-xlarge",
  "--text-scale-xlarge--line-height",
  "--text-scale-2xlarge",
  "--text-scale-2xlarge--line-height",
  "--text-scale-3xlarge",
  "--text-scale-3xlarge--line-height",
  "--text-accent-header-size",
  "--text-accent-header-line-height",
  "--text-accent-header-weight",
  "--text-header-1-size",
  "--text-header-1-line-height",
  "--text-header-1-weight",
  "--text-header-2-size",
  "--text-header-2-line-height",
  "--text-header-2-weight",
  "--text-large-size",
  "--text-large-line-height",
  "--text-large-weight",
  "--text-base-size",
  "--text-base-line-height",
  "--text-base-weight",
  "--text-small-size",
  "--text-small-line-height",
  "--text-small-weight",
  "--text-mid-size",
  "--text-mid-line-height",
  "--text-mid-weight",
  "--text-tools-size",
  "--text-tools-line-height",
  "--text-tools-weight",
  "--max-component-small",
  "--max-component-base",
  "--max-component-mid",
  "--max-component-large",
  "--button-min-width-small",
  "--button-min-width-base",
  "--button-min-width-mid",
  "--button-min-width-large",
  "--control-height-small",
  "--control-height-base",
  "--control-height-mid",
  "--control-height-large",
  "--avatar-size-small",
  "--avatar-size-base",
  "--avatar-size-mid",
  "--avatar-size-large",
  "--icon-size-xsmall",
  "--icon-size-small",
  "--icon-size-base",
  "--icon-size-mid",
  "--icon-size-large",
  "--icon-size-xlarge",
  "--icon-size-2xlarge",
  "--shadow-size",
  "--shadow-none",
  "--shadow-base",
  "--shadow-mid",
  "--shadow-large",
  "--toast-scrim-size",
  "--toast-scrim-density",
] as const;

export type DesignCssVar = (typeof designTokenNames)[number];

type ColorCssVarName = Extract<DesignCssVar, `--color-${string}`>;

/** Suffix after `--color-` (same as theme key without the `color-` prefix) */
export type ColorTokenSuffix = ColorCssVarName extends `--color-${infer S}`
  ? S
  : never;

/**
 * Reference to a color token for `style` / ripple: without a literal `var(--...)`.
 * @example colorToken("converge-ripple-neutral") // → var(--color-converge-ripple-neutral)
 */
export function colorToken<S extends ColorTokenSuffix>(suffix: S): `var(--color-${S})` {
  return `var(--color-${suffix})` as `var(--color-${S})`;
}
