export { tokensConfig, type TokensConfig } from "./config";
export {
  burneShadowScale,
  type ShadowSize,
  type ShadowLevel,
  SHADOW_CSS_VAR,
  shadowToken,
} from "./shadows";

/** Имена CSS-переменных для типобезопасного доступа и генераторов */
export const designTokenNames = [
  "--border-width",
  "--color-background",
  "--color-surface",
  "--color-border",
  "--color-foreground",
  "--color-muted",
  "--color-primary",
  "--color-primary-foreground",
  "--color-primary-hover",
  "--color-primary-tint",
  "--color-primary-tint-strong",
  "--color-indicator",
  "--color-indicator-foreground",
  "--color-secondary",
  "--color-secondary-foreground",
  "--color-secondary-hover",
  "--color-tertiary",
  "--color-tertiary-foreground",
  "--color-tertiary-hover",
  "--color-focus-ring",
  "--color-converge-ripple-primary-fill",
  "--color-converge-ripple-neutral",
  "--color-converge-ripple-neutral-muted",
  "--color-converge-ripple-danger",
  "--color-converge-ripple-info",
  "--color-converge-ripple-success",
  "--color-converge-ripple-warning",
  "--color-danger",
  "--color-danger-fill-hover",
  "--color-danger-foreground",
  "--color-success",
  "--color-success-foreground",
  "--color-success-fill-hover",
  "--color-info",
  "--color-info-foreground",
  "--color-info-fill-hover",
  "--color-warning",
  "--color-warning-foreground",
  "--color-warning-fill-hover",
  "--color-surface-tint-danger",
  "--color-surface-tint-success",
  "--color-surface-tint-info",
  "--color-surface-tint-warning",
  "--color-surface-tint-primary",

  "--color-surface-tint-danger-strong",
  "--color-surface-tint-success-strong",
  "--color-surface-tint-warning-strong",
  "--color-surface-tint-danger-foreground",
  "--color-surface-tint-success-foreground",
  "--color-surface-tint-info-foreground",
  "--color-surface-tint-warning-foreground",
  "--color-surface-tint-primary-foreground",
  "--font-family-sans",
  "--font-family-mono",
  "--space",
  "--space-xsmall",
  "--space-small",
  "--space-base",
  "--space-plus",
  "--space-mid",
  "--space-large",
  "--space-xlarge",
  "--calendar-cell-gap",
  "--size",
  "--size-scale-925",
  "--size-scale-xs",
  "--size-scale-sm",
  "--size-scale-md",
  "--size-scale-lg",
  "--size-scale-xl",
  "--size-scale-2xl",
  "--size-scale-3xl",
  "--selection-indicator-small",
  "--selection-indicator-base",
  "--selection-indicator-mid",
  "--selection-indicator-large",
  "--radius",
  "--radius-value-xsmall",
  "--radius-value-small",
  "--radius-value-base",
  "--radius-value-mid",
  "--radius-value-large",
  "--text-scale-tools",
  "--text-scale-tools--line-height",
  "--text-scale-xs",
  "--text-scale-xs--line-height",
  "--text-scale-sm",
  "--text-scale-sm--line-height",
  "--text-scale-md",
  "--text-scale-md--line-height",
  "--text-scale-lg",
  "--text-scale-lg--line-height",
  "--text-scale-xl",
  "--text-scale-xl--line-height",
  "--text-scale-2xl",
  "--text-scale-2xl--line-height",
  "--text-scale-3xl",
  "--text-scale-3xl--line-height",
  "--text-scale-4xl",
  "--text-scale-4xl--line-height",
  "--text-accent-header-size",
  "--text-accent-header-line-height",
  "--text-accent-header-weight",
  "--text-header-1-size",
  "--text-header-1-line-height",
  "--text-header-1-weight",
  "--text-header-2-size",
  "--text-header-2-line-height",
  "--text-header-2-weight",
  "--text-large-size",
  "--text-large-line-height",
  "--text-large-weight",
  "--text-base-size",
  "--text-base-line-height",
  "--text-base-weight",
  "--text-small-size",
  "--text-small-line-height",
  "--text-small-weight",
  "--text-mid-size",
  "--text-mid-line-height",
  "--text-mid-weight",
  "--text-tools-size",
  "--text-tools-line-height",
  "--text-tools-weight",
  "--max-component-small",
  "--max-component-base",
  "--max-component-mid",
  "--max-component-large",
  "--button-min-width-small",
  "--button-min-width-base",
  "--button-min-width-mid",
  "--button-min-width-large",
  "--control-height-small",
  "--control-height-base",
  "--control-height-mid",
  "--control-height-large",
  "--avatar-size-small",
  "--avatar-size-base",
  "--avatar-size-mid",
  "--avatar-size-large",
  "--icon-size-xsmall",
  "--icon-size-small",
  "--icon-size-base",
  "--icon-size-mid",
  "--icon-size-large",
  "--icon-size-xlarge",
  "--icon-size-2xlarge",
  "--ease-out",
  "--duration-fast",
  "--duration-normal",
  "--glass-blur",
  "--glass-blur-edge",
  "--glass-saturate",
  "--glass-tint",
  "--glass-tint-veil",
  "--glass-border",
  "--glass-highlight",
  "--glass-edge-falloff",
  "--shadow-size",
  "--shadow-none",
  "--shadow-sm",
  "--shadow-md",
  "--shadow-lg",
] as const;

export type DesignCssVar = (typeof designTokenNames)[number];

type ColorCssVarName = Extract<DesignCssVar, `--color-${string}`>;

/** Хвост имени после `--color-` (как в theme key без префикса `color-`) */
export type ColorTokenSuffix = ColorCssVarName extends `--color-${infer S}`
  ? S
  : never;

/**
 * Ссылка на цветовой токен для `style` / ripple: без литерала `var(--...)`.
 * @example colorToken("converge-ripple-neutral") // → var(--color-converge-ripple-neutral)
 */
export function colorToken<S extends ColorTokenSuffix>(suffix: S): `var(--color-${S})` {
  return `var(--color-${suffix})` as `var(--color-${S})`;
}
