import "@/styles.css";

export { cn } from "@/utils/cn";
export {
  type ComponentSize,
  COMPONENT_SIZES,
} from "@/components/core/utils/componentSize";
export {
  CONTROL_SIZE_LAYOUT,
  controlShellClass,
  readControlHeightPx,
  type ControlSizeLayout,
} from "@/components/core/utils/controlSizeLayout";
export {
  Button,
  buttonRippleTone,
  type ButtonProps,
  type ButtonAsyncState,
  type ButtonSize,
  type ButtonVariant,
  type ButtonStatus,
} from "@/components/core/Button";
export {
  CloseButton,
  type CloseButtonProps,
  type CloseButtonSize,
  type CloseButtonVariant,
} from "@/components/core/CloseButton";
export {
  GlassSurface,
  GlassShaderLayer,
  GlassBackdrop,
  type GlassSurfaceProps,
  type GlassShaderLayerProps,
  type GlassBackdropProps,
} from "@/components/core/GlassSurface";
export {
  LiquidGlass,
  resetLiquidGlassSnapshot,
  type LiquidGlassProps,
  type LiquidGlassShape,
  type LiquidGlassControls,
} from "@/components/core/LiquidGlass";
export {
  Ripple,
  RIPPLE_COLOR,
  type RippleProps,
  type RippleColor,
  type RippleDirection,
} from "@/components/core/Ripple";
export {
  Expandable,
  type ExpandableProps,
  type ExpandableRootProps,
  type ExpandableTriggerProps,
  type ExpandableMessageProps,
  type ExpandableIconProps,
  type ExpandableContentProps,
  type ExpandableTitleProps,
  type ExpandableDescriptionProps,
  type ExpandableChevronProps,
  type ExpandablePanelProps,
} from "@/components/core/Expandable";
export {
  Alert,
  resolveAlertStatus,
  resolveAlertLiveRole,
  type AlertProps,
  type AlertStatus,
  type AlertLiveRole,
  type AlertIndicatorProps,
  type AlertContentProps,
  type AlertMessageProps,
  type AlertTitleProps,
  type AlertDescriptionProps,
  type AlertActionProps,
} from "@/components/core/Alert";
export {
  Accordion,
  type AccordionProps,
  type AccordionItemProps,
  type AccordionHeadingProps,
  type AccordionTriggerProps,
  type AccordionMessageProps,
  type AccordionIconProps,
  type AccordionContentProps,
  type AccordionTitleProps,
  type AccordionDescriptionProps,
  type AccordionIndicatorProps,
  type AccordionPanelProps,
  type AccordionBodyProps,
} from "@/components/composite/Accordion";
export { Form, type FormProps } from "@/components/composite/Form";
export {
  CheckboxGroup,
  type CheckboxGroupProps,
  type CheckboxGroupSelection,
  type CheckboxGroupOrientation,
  type CheckboxGroupHintProps,
  type CheckboxGroupLabelProps,
  type CheckboxGroupLegendProps,
  type CheckboxGroupListProps,
} from "@/components/composite/CheckboxGroup";
export {
  RadioGroup,
  type RadioGroupProps,
  type RadioGroupOrientation,
  type RadioGroupHintProps,
  type RadioGroupErrorProps,
  type RadioGroupLabelProps,
  type RadioGroupLegendProps,
  type RadioGroupListProps,
} from "@/components/composite/RadioGroup";
export {
  ButtonGroup,
  ButtonGroupText,
  type ButtonGroupProps,
  type ButtonGroupTextProps,
  type ButtonGroupOrientation,
  type ButtonGroupSegment,
} from "@/components/composite/ButtonGroup";
export {
  ToggleButtonGroup,
  type ToggleButtonGroupProps,
  type ToggleButtonGroupType,
  type ToggleButtonGroupOrientation,
} from "@/components/composite/ToggleButtonGroup";
export {
  AlertDialog,
  footerButtonSizeForAlertDialog,
  primaryButtonVariantForAlertTone,
  primaryButtonStatusForAlertTone,
  useAlertDialog,
  type AlertDialogProps,
  type AlertDialogSize,
  type AlertDialogHeaderProps,
  type AlertDialogIndicatorProps,
  type AlertDialogTitleProps,
  type AlertDialogDescriptionProps,
  type AlertDialogBodyProps,
  type AlertDialogFooterProps,
  type AlertDialogCloseProps,
} from "@/components/composite/AlertDialog";
export {
  Dialog,
  type DialogProps,
  type DialogHeaderProps,
  type DialogTitleProps,
  type DialogDescriptionProps,
  type DialogBodyProps,
  type DialogFooterProps,
  type DialogCloseProps,
} from "@/components/core/Dialog";
export {
  Toast,
  ToastContext,
  useToastContext,
  useToast,
  type ToastStatus,
  type ToastPlacement,
  type ToastProviderProps,
  type ToastRootProps,
  type ToastIndicatorProps,
  type ToastMessageProps,
  type ToastContentProps,
  type ToastTitleProps,
  type ToastDescriptionProps,
  type ToastActionButtonProps,
  type ToastCloseButtonProps,
  type AddToastOpts,
  type PromiseToastOpts,
  type ToastContextValue,
} from "@/components/core/Toast";
export {
  Drawer,
  type DrawerProps,
  type DrawerPlacement,
  type DrawerSize,
  type DrawerBackdropProps,
  type DrawerHandleProps,
  type DrawerHeaderProps,
  type DrawerHeadingBlockProps,
  type DrawerTitleProps,
  type DrawerDescriptionProps,
  type DrawerBodyProps,
  type DrawerFooterProps,
  type DrawerCloseProps,
} from "@/components/core/Drawer";
export {
  Field,
  FieldSet,
  FieldSetGroup,
  FieldSetActions,
  FieldLegend,
  FieldLegendHeader,
  joinFieldDescribedBy,
  fieldHintId,
  fieldErrorId,
  useFieldSetHintId,
  useFieldSetErrorId,
  type FieldRootProps,
  type FieldHintProps,
  type FieldHintStatus,
  type FieldLabelProps,
  type FieldErrorProps,
  type FieldSetProps,
  type FieldSetGroupProps,
  type FieldSetActionsProps,
  type FieldLegendProps,
  type FieldLegendHeaderProps,
  type FieldSetSize,
} from "@/components/core/Field";
export {
  Label,
  type LabelProps,
  type FieldLabelContextValue,
} from "@/components/core/Label";
export {
  Link,
  type LinkProps,
  type LinkSize,
  type LinkIconPosition,
} from "@/components/core/Link";
export {
  Loading,
  type LoadingProps,
  type LoadingSize,
  type LoadingColor,
} from "@/components/core/Loading";
export {
  Input,
  type InputProps,
  type InputSimpleProps,
  type InputSize,
  type InputVariant,
  type InputStatus,
  type InputRootProps,
  type InputHintProps,
  type InputErrorProps,
} from "@/components/core/Input";
export {
  TextArea,
  type TextAreaProps,
  type TextAreaSimpleProps,
  type TextAreaSize,
  type TextAreaVariant,
  type TextAreaStatus,
  type TextAreaRootProps,
  type TextAreaHintProps,
  type TextAreaErrorProps,
} from "@/components/core/TextArea";
export {
  ComboBox,
  type ComboBoxOption,
  type ComboBoxRootProps,
  type ComboBoxSimpleProps,
  type ComboBoxHintProps,
  type ComboBoxInputGroupProps,
  type ComboBoxInputProps,
  type ComboBoxTriggerProps,
  type ComboBoxPopoverProps,
} from "@/components/core/ComboBox";
export {
  ListBox,
  useListBox,
  type ListBoxRootProps,
  type ListBoxItemProps,
  type ListBoxSize,
} from "@/components/core/ListBox";
export {
  Checkbox,
  type CheckboxProps,
  type CheckboxVariant,
  type CheckboxSize,
} from "@/components/core/Checkbox";
export {
  SelectionIndicator,
  type SelectionIndicatorProps,
  type SelectionIndicatorSize,
  type SelectionIndicatorVariant,
} from "@/components/core/SelectionIndicator";
export {
  SelectionThumb,
  SelectionThumbIcon,
  type SelectionThumbProps,
  type SelectionThumbIconProps,
} from "@/components/core/SelectionThumb";
export {
  Radio,
  type RadioProps,
  type RadioRootProps,
  type RadioControlProps,
  type RadioIndicatorProps,
  type RadioContentProps,
  type RadioLabelProps,
  type RadioHintProps,
  type RadioSize,
} from "@/components/core/Radio";
export {
  Switch,
  type SwitchControlProps,
  type SwitchSize,
  type SwitchLabelPosition,
  type SwitchRootProps,
  type SwitchSimpleProps,
  type SwitchHintProps,
} from "@/components/core/Switch";
export {
  Tabs,
  useTabsContext,
  type TabsRootProps,
  type TabsListProps,
  type TabsTabProps,
  type TabsPanelProps,
  type TabsSize,
  type TabsOrientation,
  type TabsVariant,
} from "@/components/core/Tabs";
export {
  ToggleButton,
  type ToggleButtonProps,
  type ToggleButtonSize,
  type ToggleButtonVariant,
} from "@/components/core/ToggleButton";
export {
  Slider,
  sliderThicknessToCss,
  type SliderTrackProps,
  type SliderSingleProps,
  type SliderRangeProps,
  type SliderOrientation,
  type SliderSize,
  type SliderThickness,
  type SliderRailProps,
  type SliderFillProps,
  type SliderThumbProps,
  type SliderIconProps,
  type SliderThumbKind,
  type SliderRootProps,
  type SliderHeaderProps,
  type SliderValueProps,
  type SliderHintProps,
} from "@/components/core/Slider";
export {
  Meter,
  type MeterTrackProps,
  type MeterSize,
  type MeterOrientation,
  type MeterRootProps,
  type MeterHeaderProps,
  type MeterValueProps,
} from "@/components/core/Meter";
export {
  ProgressBar,
  type ProgressBarTrackProps,
  type ProgressBarSize,
  type ProgressBarOrientation,
  type ProgressBarRootProps,
  type ProgressBarHeaderProps,
  type ProgressBarValueProps,
  type ProgressBarHintProps,
} from "@/components/core/ProgressBar";
export {
  SearchInput,
  type SearchInputProps,
  type SearchInputSize,
} from "@/components/core/SearchInput";
export { Text, type TextProps, type TextVariant } from "@/components/core/Text";
export {
  Card,
  type CardPressEvent,
  type CardProps,
  type CardVariant,
  type CardHeaderProps,
  type CardBodyProps,
  type CardTitleProps,
  type CardDescriptionProps,
  type CardFooterProps,
} from "@/components/core/Card";
export {
  Avatar,
  AvatarGroup,
  type AvatarProps,
  type AvatarSize,
  type AvatarImageProps,
  type AvatarFallbackProps,
  type AvatarGroupProps,
} from "@/components/core/Avatar";
export {
  Tooltip,
  type TooltipVariant,
  type TooltipSize,
  type TooltipSide,
  type TooltipRootProps,
  type TooltipTriggerProps,
  type TooltipContentProps,
  type TooltipArrowProps,
  type TooltipPanelProps,
  type TooltipIndicatorProps,
  type TooltipTitleProps,
  type TooltipDescriptionProps,
} from "@/components/core/Tooltip";
export {
  Popover,
  type PopoverRootProps,
  type PopoverTriggerProps,
  type PopoverContentProps,
  type PopoverHeaderProps,
  type PopoverLabelProps,
  type PopoverHintProps,
  type PopoverBodyProps,
  type PopoverArrowProps,
  type PopoverSide,
  type PopoverSize,
  type PopoverContentGap,
} from "@/components/core/Popover";
export {
  Breadcrumbs,
  type BreadcrumbsProps,
  type BreadcrumbsListProps,
  type BreadcrumbsItemProps,
} from "@/components/core/Breadcrumbs";
export {
  Pagination,
  type PaginationProps,
  type PaginationSummaryProps,
  type PaginationContentProps,
  type PaginationItemProps,
  type PaginationNavButtonProps,
  type PaginationPageProps,
  type PaginationEllipsisProps,
  type PaginationPagesProps,
} from "@/components/core/Pagination";
export {
  Separator,
  type SeparatorProps,
  type SeparatorOrientation,
} from "@/components/core/Separator";
export {
  Surface,
  type SurfaceProps,
  type SurfaceVariant,
  type SurfaceShadow,
  type SurfacePadding,
  type SurfaceRadius,
} from "@/components/core/Surface";
export {
  Dropdown,
  DropdownTrigger,
  DropdownPopover,
  DropdownContent,
  DropdownGroup,
  DropdownLabel,
  DropdownSeparator,
  DropdownItem,
  DropdownItemLabel,
  DropdownItemHint,
  DropdownItemIcon,
  DropdownItemIndicator,
  DropdownSub,
  DropdownSubTrigger,
  DropdownSubContent,
  type DropdownProps,
  type DropdownTriggerProps,
  type DropdownPopoverProps,
  type DropdownContentProps,
  type DropdownGroupProps,
  type DropdownLabelProps,
  type DropdownSeparatorProps,
  type DropdownItemProps,
  type DropdownItemLabelProps,
  type DropdownItemHintProps,
  type DropdownItemIconProps,
  type DropdownItemIndicatorProps,
  type DropdownItemVariant,
  type DropdownSubProps,
  type DropdownSubTriggerProps,
  type DropdownSubContentProps,
} from "@/components/core/Dropdown";
export {
  Badge,
  BadgeAnchor,
  type BadgeProps,
  type BadgeVariant,
  type BadgeStatus,
  type BadgeSize,
  type BadgePlacement,
  type BadgeIconPosition,
  type BadgeAnchorProps,
} from "@/components/core/Badge";
export {
  configureMotion,
  getMotionConfig,
  type MotionConfig,
} from "@/components/core/utils/motionConfig";
export {
  MOTION_INTERACTIVE_MS,
  MOTION_INTERACTIVE_EASE,
  MOTION_TOOLTIP_MS,
  MOTION_HOVER_LIFT_SCALE,
  MOTION_BADGE_ANCHOR_HOVER_LIFT_SCALE,
  MOTION_PRESS_SQUEEZE_SCALE,
  MOTION_RIPPLE_DEFAULT_DURATION_MS,
  MOTION_RIPPLE_DEFAULT_OPACITY_FROM,
  MOTION_RIPPLE_EXPANDABLE_DURATION_MS,
  MOTION_RIPPLE_EXPANDABLE_OPACITY_FROM,
  MOTION_RIPPLE_EASE_CSS,
  MOTION_RIPPLE_MIN_SCALE,
  MOTION_FEEDBACK_EXPAND_MS,
} from "@/components/core/utils/motionTokens";
export { useConvergeRipples } from "@/components/core/utils/useConvergeRipples";
export { ConvergeRippleLayer } from "@/components/core/utils/pressRipple";
export {
  createConvergeRippleAtPointer,
  createConvergeRippleFromPointer,
  type ConvergeRipple,
} from "@/components/core/utils/convergeRippleGeometry";
export {
  animateInteractiveHoverLift,
  animateInteractivePressSqueeze,
  initElementShadow,
  prefersReducedInteractiveHoverLift,
  readShadowSize,
  shadowLg,
  shadowMd,
  shadowNone,
  shadowSm,
  shouldSkipInteractiveHoverLift,
  useInteractiveHoverLiftContainerHandlers,
  useInteractiveHoverLiftOnContainer,
  type HoverShadowConfig,
} from "@/components/core/utils/hoverInteractiveLift";
export {
  colorToken,
  tokensConfig,
  designTokenNames,
  burneShadowScale,
  shadowToken,
  SHADOW_CSS_VAR,
  type ColorTokenSuffix,
  type TokensConfig,
  type DesignCssVar,
  type ShadowSize,
  type ShadowLevel,
} from "@/tokens";
export { gsap, useGSAP, killMotion, ensureRippleEase } from "@/components/core/utils/gsapMotion";
export {
  Table,
  TABLE_ROW_TONE_SURFACE,
  type TableProps,
  type TableVariant,
  type TableRowTone,
  type TableScrollContainerProps,
  type TableContentProps,
  type TableHeaderProps,
  type TableColumnProps,
  type TableColumnRenderProps,
  type TableBodyProps,
  type TableRowProps,
  type TableCellProps,
  type TableFooterProps,
  type SortDescriptor,
  type SortDirection,
  type SelectionMode,
  type Selection,
} from "@/components/core/Table";
export {
  Calendar,
  RU_LOCALE,
  useCalendar,
  type CalendarProps,
  type CalendarHeaderProps,
  type CalendarGridProps,
  type CalendarFooterProps,
  type CalendarMode,
  type CalendarView,
  type CalendarVariant,
  type CalendarSize,
  type CalendarRangeValue,
  type CalendarLocale,
} from "@/components/core/Calendar";

export {
  ColorPicker,
  ColorSlider,
  ColorSliderTrack,
  ColorSwatch,
  useColorPicker,
  hsvaToHex,
  hexToHsva,
  hsvaToRgba,
  rgbaToHsva,
  rgbaToHex,
  hexToRgba,
  hsvaToColorString,
  hueToRgbString,
  type ColorPickerProps,
  type ColorPickerTriggerProps,
  type ColorPickerContentProps,
  type ColorPickerSize,
  type ColorSliderTrackProps,
  type ColorSliderRootProps,
  type ColorChannel,
  type ColorSliderSize,
  type ColorSliderOrientation,
  type ColorSwatchProps,
  type ColorSwatchSize,
  type ColorSwatchShape,
  type HSVA,
  type RGBA,
} from "@/components/core/ColorPicker";

export {
  TimeField,
  TimeFieldControl,
  TimeFieldHint,
  TimeFieldError,
  type TimeFieldRootProps,
  type TimeFieldControlProps,
  type TimeFieldHintProps,
  type TimeFieldErrorProps,
  type TimeFieldSize,
  type TimeFieldStatus,
  type TimeFieldVariant,
  type TimeFieldFormat,
} from "@/components/core/TimeField";

export {
  Skeleton,
  type SkeletonProps,
  type SkeletonCircleProps,
  type SkeletonTextProps,
  type SkeletonVariant,
  type SkeletonRadius,
} from "@/components/core/Skeleton";

export {
  Disclosure,
  DisclosureGroup,
  type DisclosureProps,
  type DisclosureGroupProps,
  type DisclosureTriggerProps,
  type DisclosureContentProps,
  type DisclosureVariant,
  type DisclosureSize,
  type DisclosureIconPos,
} from "@/components/core/Disclosure";
